# Generated by Django 4.1.10 on 2023-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ifsc',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
