# Generated by Django 4.1.10 on 2023-08-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account')], default='none', max_length=20),
        ),
    ]
