# Generated by Django 4.1.10 on 2023-08-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_balance_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
