# Generated by Django 4.1.10 on 2023-08-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_wallettransaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletTransaction',
            new_name='AccountTransaction',
        ),
    ]
