# Generated by Django 4.1.10 on 2023-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_cardrequest_carddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='profession',
            field=models.CharField(choices=[('Private job', 'Private job'), ('Govt job', 'Govt job'), ('Bussiness', 'Bussiness'), ('Student', 'Student')], default='none', max_length=20),
        ),
    ]
