# Generated by Django 3.2.20 on 2023-08-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_cardrequest_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='card_limit',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
